-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_visits" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "child_id" INTEGER NOT NULL,
    "doctor_id" INTEGER NOT NULL,
    "visit_date" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "visit_type" TEXT,
    "visit_place" TEXT,
    "visit_time" TEXT,
    "ticket_number" TEXT,
    "referring_doctor_id" INTEGER,
    "current_weight" REAL,
    "current_height" REAL,
    "bmi" REAL,
    "bsa" REAL,
    "disease_onset" TEXT,
    "disease_course" TEXT,
    "treatment_before_visit" TEXT,
    "heredity_data" TEXT,
    "birth_data" TEXT,
    "feeding_data" TEXT,
    "infectious_diseases_data" TEXT,
    "allergy_status_data" TEXT,
    "blood_pressure_systolic" INTEGER,
    "blood_pressure_diastolic" INTEGER,
    "pulse" INTEGER,
    "respiratory_rate" INTEGER,
    "temperature" REAL,
    "oxygen_saturation" INTEGER,
    "consciousness_level" TEXT,
    "general_condition" TEXT,
    "consciousness" TEXT,
    "skin_mucosa" TEXT,
    "lymph_nodes" TEXT,
    "musculoskeletal" TEXT,
    "respiratory" TEXT,
    "cardiovascular" TEXT,
    "abdomen" TEXT,
    "urogenital" TEXT,
    "nervous_system" TEXT,
    "complaints" TEXT NOT NULL,
    "complaints_json" TEXT,
    "physical_exam" TEXT,
    "additional_examination_plan" TEXT,
    "laboratory_tests" TEXT,
    "instrumental_tests" TEXT,
    "consultation_requests" TEXT,
    "physiotherapy" TEXT,
    "is_first_time_diagnosis" BOOLEAN,
    "is_trauma" BOOLEAN,
    "primary_diagnosis" TEXT,
    "complications" TEXT,
    "comorbidities" TEXT,
    "primary_diagnosis_id" INTEGER,
    "complication_ids" TEXT,
    "comorbidity_ids" TEXT,
    "prescriptions" TEXT NOT NULL DEFAULT '[]',
    "recommendations" TEXT,
    "outcome" TEXT,
    "patient_route" TEXT,
    "hospitalization_indication" TEXT,
    "next_visit_date" DATETIME,
    "informed_consent_id" INTEGER,
    "disability_certificate" BOOLEAN,
    "preferential_prescription" BOOLEAN,
    "certificate_issued" BOOLEAN,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "notes" TEXT,
    "created_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" DATETIME NOT NULL,
    CONSTRAINT "visits_child_id_fkey" FOREIGN KEY ("child_id") REFERENCES "children" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "visits_doctor_id_fkey" FOREIGN KEY ("doctor_id") REFERENCES "users" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "visits_primary_diagnosis_id_fkey" FOREIGN KEY ("primary_diagnosis_id") REFERENCES "diseases" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_visits" ("abdomen", "additional_examination_plan", "blood_pressure_diastolic", "blood_pressure_systolic", "bmi", "bsa", "cardiovascular", "certificate_issued", "child_id", "comorbidities", "comorbidity_ids", "complaints", "complaints_json", "complication_ids", "complications", "consciousness", "consciousness_level", "consultation_requests", "created_at", "current_height", "current_weight", "disability_certificate", "doctor_id", "general_condition", "hospitalization_indication", "id", "informed_consent_id", "instrumental_tests", "is_first_time_diagnosis", "is_trauma", "laboratory_tests", "lymph_nodes", "musculoskeletal", "nervous_system", "next_visit_date", "notes", "outcome", "oxygen_saturation", "patient_route", "physical_exam", "physiotherapy", "preferential_prescription", "prescriptions", "primary_diagnosis", "primary_diagnosis_id", "pulse", "recommendations", "referring_doctor_id", "respiratory", "respiratory_rate", "skin_mucosa", "status", "temperature", "ticket_number", "updated_at", "urogenital", "visit_date", "visit_place", "visit_time", "visit_type") SELECT "abdomen", "additional_examination_plan", "blood_pressure_diastolic", "blood_pressure_systolic", "bmi", "bsa", "cardiovascular", "certificate_issued", "child_id", "comorbidities", "comorbidity_ids", "complaints", "complaints_json", "complication_ids", "complications", "consciousness", "consciousness_level", "consultation_requests", "created_at", "current_height", "current_weight", "disability_certificate", "doctor_id", "general_condition", "hospitalization_indication", "id", "informed_consent_id", "instrumental_tests", "is_first_time_diagnosis", "is_trauma", "laboratory_tests", "lymph_nodes", "musculoskeletal", "nervous_system", "next_visit_date", "notes", "outcome", "oxygen_saturation", "patient_route", "physical_exam", "physiotherapy", "preferential_prescription", "prescriptions", "primary_diagnosis", "primary_diagnosis_id", "pulse", "recommendations", "referring_doctor_id", "respiratory", "respiratory_rate", "skin_mucosa", "status", "temperature", "ticket_number", "updated_at", "urogenital", "visit_date", "visit_place", "visit_time", "visit_type" FROM "visits";
DROP TABLE "visits";
ALTER TABLE "new_visits" RENAME TO "visits";
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;
